### PR TITLE
removes 'publish data format' section from the developer contribution…

### PR DESCRIPTION
**Pull request by mattlucht**
removes 'publish data format' section from the developer contribution…

### CODE REVIEW

**Comment by Christine-horrocks** [comment]
The change looks simple enough, but there seems to be an issue with some of the npm dependancies. Could you npm install locally to see if that helps?

**Comment by mattlucht** [comment]
@Christine-horrocks I ran npm install, everything seemed fine here?

**Comment by Christine-horrocks** [comment]
From what I can find it might be to do with the package-lock.json file. Could you delete that file, then run npm install again?
https://github.com/solid/node-solid-server/issues/690

**Comment by mattlucht** [comment]
@Christine-horrocks I've deleted package-lock.json and re-run npm install. Want me to commit that change?

**Comment by Christine-horrocks** [comment]
Yes please, commit the change and it should get added to the pull request

**Comment by Christine-horrocks** [comment]
Ok googling round number two. Npm ci seems to be linked to the cache: in the .travis.yml file. There are suggestions that by removing the cache, then running npm install and committing, this problem might be fixed. 

https://github.com/travis-ci/travis-ci/issues/10113 

If you could go into the .travis.yml file. Go to where it says cache and remove the indented lines below, down to and including -node modules. Then npm install and then commit.

**Comment by mattlucht** [comment]
thanks @Christine-horrocks, trying that now

**Comment by Christine-horrocks** [comment]
Rubbish, still getting exactly the same errors.

**Pull request merged**
